### ISSUE TITLE
Downgrade Microsoft.ApplicationInsights.AspNetCore minimum version to 2.12.0

### ISSUE THREAD

**Issue by jouz3** [christianacca/ApplicationInsights.ProblemDetails#2]
Can the **Microsoft.ApplicationInsights.AspNetCore** minimum version dependency be changed to 2.12.0?
There's stil al lot o people using that version because of breaking changes when upgrading.

I have cloned the repo and tested using that version with success.
I'm open to submit a PR with the change.

**Comment by christianacca** [comment]
Sure send a PR.

As a workaround your app can also take a direct dependency on `Microsoft.ApplicationInsights.AspNetCore` v2.12.0. That way .net will prefer the v2.12.0 version over v2.14.0 that is indirectly referenced by `CcAcca.ApplicationInsights.ProblemDetails` (see https://docs.microsoft.com/en-us/nuget/concepts/dependency-resolution#nearest-wins)
